<?php

namespace PnShop\Api;

use Dedoc\Scramble\Scramble;
use Dedoc\Scramble\Support\Generator\OpenApi;
use Dedoc\Scramble\Support\Generator\Operation;
use Dedoc\Scramble\Support\Generator\Parameter;
use Dedoc\Scramble\Support\Generator\Schema;
use Dedoc\Scramble\Support\Generator\SecurityScheme;
use Dedoc\Scramble\Support\Generator\Server;
use Dedoc\Scramble\Support\Generator\Types\IntegerType;
use Dedoc\Scramble\Support\Generator\Types\StringType;
use Dedoc\Scramble\Support\Generator\Types\Type;
use Dedoc\Scramble\Support\RouteInfo;
use Illuminate\Routing\Route;
use PnShop\Api\Http\Middleware\Idempotent;
use PnShop\Api\Http\Middleware\StoreCustomer;
use PnShop\Foundation\PnShop;

/**
 * OpenAPI documents for the two APIs, generated by Scramble (a development dependency).
 * Locally they are browsable at /docs/api/store and /docs/api/admin; `composer api-docs`
 * exports them to docs/api/*.json for the repository.
 */
final class OpenApiDocs
{
    /** Routes answered with cursor pagination. */
    private const PAGINATED = [
        'api.store.products.index', 'api.store.pages.index', 'api.store.account.orders',
        'api.admin.products.index', 'api.admin.variants.index', 'api.admin.brands.index', 'api.admin.orders.index',
        'api.admin.customers.index', 'api.admin.pages.index', 'api.admin.promotions.index', 'api.admin.returns.index',
    ];

    public static function register(): void
    {
        if (! class_exists(Scramble::class)) {
            return;
        }

        $document = fn (string $prefix) => function (OpenApi $openApi) use ($prefix): void {
            $openApi->secure(SecurityScheme::http('bearer'));
            // Relative, so the documents fit every installation.
            $openApi->servers = [new Server('/'.$prefix)];
        };

        // Registered first: a new API starts as a copy of the default one's current setup.
        Scramble::registerApi('admin', self::config(ApiServiceProvider::ADMIN_PREFIX, 'PN Shop Admin API', <<<'MD'
                Integrations (ERP, accounting, PIM) with staff tokens created under System → API tokens or with `php artisan pnshop:api-token`.

                * **Permissions:** a token's abilities are permission keys, so a call needs the token ability and the owner's permission.
                * **Errors:** `application/problem+json` with a stable `code`.
                * **Lists:** cursor-paginated, with `filter[updated_since]` for incremental sync.
                MD))
            ->routes(fn (Route $route) => str_starts_with($route->uri, ApiServiceProvider::ADMIN_PREFIX.'/'))
            ->expose(ui: 'docs/api/admin', document: 'docs/api/admin.json')
            ->withOperationTransformers(self::commonParameters(...))
            ->afterOpenApiGenerated($document(ApiServiceProvider::ADMIN_PREFIX));

        Scramble::configure()
            ->useConfig(self::config(ApiServiceProvider::STORE_PREFIX, 'PN Shop Store API', <<<'MD'
                Catalog, content, cart, checkout and customer accounts for headless storefronts and apps.

                * **Authentication:** optional. Customers sign in with `POST /auth/login` and send `Authorization: Bearer <token>`.
                * **Guest carts:** send the cart `token` from cart responses as the `X-Cart-Token` header.
                * **Language:** set with `?locale=` or `Accept-Language`.
                * **Errors:** `application/problem+json` with a stable `code`.
                * **Retries:** send `Idempotency-Key` when placing orders.
                MD))
            ->routes(fn (Route $route) => str_starts_with($route->uri, ApiServiceProvider::STORE_PREFIX.'/'))
            ->expose(ui: 'docs/api/store', document: 'docs/api/store.json')
            ->withOperationTransformers(self::commonParameters(...))
            ->afterOpenApiGenerated($document(ApiServiceProvider::STORE_PREFIX));
    }

    /**
     * Parameters handled by shared code, which Scramble cannot see in the controllers:
     * cursor pagination, the guest cart header, the response language and idempotency keys.
     */
    public static function commonParameters(Operation $operation, RouteInfo $routeInfo): void
    {
        $route = $routeInfo->route;
        $parameters = [
            self::parameter('locale', 'query', new StringType, 'Response language (a store language code); defaults to Accept-Language, then the store default.'),
        ];

        if (in_array($route->getName(), self::PAGINATED, true)) {
            $parameters[] = self::parameter('per_page', 'query', new IntegerType, 'Items per page, 1 to 100 (default 20).');
            $parameters[] = self::parameter('cursor', 'query', new StringType, 'The next_cursor or prev_cursor of a previous page.');
        }

        if (str_starts_with((string) $route->getName(), 'api.store.cart') || str_starts_with((string) $route->getName(), 'api.store.checkout')) {
            $parameters[] = self::parameter(StoreCustomer::CART_HEADER, 'header', new StringType, 'Guest cart token (from a cart response). Not needed with a customer token.');
        }

        if (in_array('pnshop.idempotent', $route->gatherMiddleware(), true)) {
            $parameters[] = self::parameter(Idempotent::HEADER, 'header', new StringType, 'Unique key (e.g. a UUID) that makes retries safe: a repeat within 24 hours returns the first response.');
        }

        $operation->addParameters($parameters);
    }

    private static function parameter(string $name, string $in, Type $type, string $description): Parameter
    {
        return Parameter::make($name, $in)->setSchema(Schema::fromType($type))->description($description);
    }

    /**
     * @return array<string, mixed>
     */
    private static function config(string $path, string $title, string $description): array
    {
        return array_replace_recursive((array) config('scramble', []), [
            'api_path' => $path,
            'info' => ['version' => PnShop::VERSION, 'description' => $description],
            'ui' => ['title' => $title],
        ]);
    }
}
